### ISSUE TITLE
Cannot login to tenant UI application

### ISSUE THREAD

**Issue by hosamshahin** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#10]
After provisioning a pooled or siloed tenant I got an email with app URL, username, and password. In the app UI when I click on login button I got the following error in the browser console: 

ERROR TypeError: Cannot read property 'usePushedAuthorisationRequests' of null

**Comment by anubhavynr** [comment]
Hi, Are you still facing this issue?

I will look into this.

**Comment by anubhavynr** [comment]
can you please let us know what version of Angular you are using?

**Comment by anubhavynr** [comment]
We were not able to reproduce this so closing for now. Please reopen and provide the version of Angular and Node you are using.
