### ISSUE TITLE
[Question]: Execution logging as Pre-requisite?

### ISSUE THREAD

**Issue by hffmnn** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#11]
Hi.

Can you elaborate on this, why this is needed (in terms of functionality)? Also as far as I know this creates a lot of logging and might get expensive  with a lot of usage?

> Ensure that CloudWatch log role ARN is set for the API Gateway. In order to do so, go to the API Gateway page, inside AWS Console, and click on any one of the REST APIs listed in the console (You might have to create an Example REST API if you don't have one created.). Click on Settings from the left navigation bar and provide an IAM role that have access to publish logs to CloudWatch. Refer this link if you need more details.

And: Is there really no API for that? Does it need to be done manually?

**Comment by anubhavynr** [comment]
We enabled this mostly to debug any problems while executing the request. Sure it will cost, but in production you can also expire the logs after X days. But if you don't have this enabled it will be tough to debug issues, in cases where the error happened during invoking the lambda (permission issues).

It is actually only few lines of Cloudformation to make this happen, instead of console. But in most cases people had already enabled it and the intent was not to overwrite the role you already had assigned. Below the code to deploy this.


ApiGatewayCloudWatchPublishRole:
    Type: AWS::IAM::Role     
    Properties:
      Path: '/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs        
  
  AttachCloudWatchRoleToApiGateway:
    Type: AWS::ApiGateway::Account
    Properties: 
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchPublishRole.Arn

**Comment by hffmnn** [comment]
Ah ok, I understand. 
So as this is mainly for debugging permissions, one solution could be to enable this only in the non-production environments. There shouldn't be any role issues on production if everything was deployed and tested via IaC in the other environments, right (🤞)?

Thanks for the clarification.

**Comment by anubhavynr** [comment]
@hffmnn : I have personally found it useful for that purpose, but there are few other benefits. As per [this link](https://aws.amazon.com/premiumsupport/knowledge-center/api-gateway-cloudwatch-logs/), below are all the things this log can help you with:

Execution logs contain information that you can use to identify and troubleshoot most API errors. For example:

- The requests that your API receives.
- The integration backend responses from your API.
- The response provided by Lambda authorizers.
- The requestId for AWS integration endpoints.
- Information on if a provided API key was authorized or not.

**Comment by anubhavynr** [comment]
Closing this issue for now. Please feel free to reopen if needed

**Comment by hffmnn** [comment]
Thanks again for the info 👍
