### ISSUE TITLE
Lab 3 - authorization via browser fails -  authorizedCallback Validation, iat rejected id_token was issued too far away from the current time

### ISSUE THREAD

**Issue by chalcrow** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#15]
At the following stage of the workshop I encountered an issue when attempted to authorize via the client Angular SaaS application - https://catalog.us-east-1.prod.workshops.aws/v2/workshops/b0c6ad36-0a4b-45d8-856b-8a64f0ac76bb/en-US/lab3/45-login-saas-app

I get a login failure screen, and the Chrome browser console shows the following error:

`authorizedCallback Validation, iat rejected id_token was issued too far away from the current time`

I tracked this back to a behaviour of the following version of the angular-auth-oidc-client library, which had been installed during the npm install - https://github.com/damienbod/angular-auth-oidc-client/releases/tag/release_11_6_11https://github.com/damienbod/angular-auth-oidc-client/releases/tag/release_11_6_11

I'm able to work around it by setting a high value (e.g. 20000 seconds) for the config setting `maxIdTokenIatOffsetAllowedInSeconds` in the following file: `/aws-serverless-saas-workshop/Lab3/client/Application/src/app/views/auth/auth-configuration.service.ts`

I'm wondering if the current deployment can result in the client and server times being unsynchronised, and maybe this is the cause? There's a discussion here that includes comments from the primary author of the angular-auth-oidc-client library - https://github.com/damienbod/angular-auth-oidc-client/issues/175

**Comment by ujwalbukka** [comment]
Closing this issue. Please re-open if need so.
