### ISSUE TITLE
Unable to login to Tenant Application (duplicate of closed #10)

### ISSUE THREAD

**Issue by lspellman-opsguru** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#16]
Exact same issue as previously reported [here](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/issues/10):  Click the Login button, receive:

**ERROR TypeError: Cannot read property 'usePushedAuthorisationRequests' of null**

After creating tenant in the SaaS Admin app, attempting to login to Tenant. Noteably, this is during Lab 5 of the workshop where tiering has been introduced. PRIOR to this, logging into Tenant app was successful. But at [this stage in the workshop](https://catalog.us-east-1.prod.workshops.aws/v2/workshops/b0c6ad36-0a4b-45d8-856b-8a64f0ac76bb/en-US/lab5/66-tenant-routing), it's not. 

I'll be going back through the deployment steps in that Lab to determine if I can isolate the cause.

**Comment by lspellman-opsguru** [comment]
I've found the issue. There is a mechanism to login the user, but it requires that the user click on Products or Services first to trigger the Unauthorized workflow. That brings up a form to say what Tenant the user is a part of. That triggers the setTenantConfig method in the auth-configuration-service.ts file (AuthConfigurationService class). Then, when user clicks the Login button, it is configured to work correctly. Obviously, this is for the shared pool tenants.

Looks like the best fix would be to refactor and incorporate the tenant selection into the Login button workflow. Short of that though, the workaround is to click to an unauthorized page first.

**Comment by ujwalbukka** [comment]
Thanks for pointing this out. Currently, in the serverless saas reference solution we have fixed the code to redirect to Unauthorized workflow. As you mentioned, tenant selection is also a viable option.
