### ISSUE TITLE
Error: Template file not found at /home/ec2-user/environment/aws-saas-factory-ref-solution-serverless-saas/server/template.yml

### ISSUE THREAD

**Issue by chalcrow** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#19]
When running the main ./deployment.sh on a Cloud 9 instance on EC2 (in Singapore region), I get the following during the common resource bootstrapping stage:

[11034] Failed to execute script __main__
+ sam deploy --config-file samconfig-bootstrap.toml --region=ap-southeast-1 --parameter-overrides AdminEmailParameter=chris.halcrow@elenium.com
Error: Template file not found at /home/ec2-user/environment/aws-saas-factory-ref-solution-serverless-saas/server/template.yml
+ [[ 1 -ne 0 ]]
+ exit 1

I don't find anything when I search the code for `template.yml` so I'm not sure what's attempting to reference this. The file isn't present in the solution. I was able to successfully run ./deployment.sh previously, in the Sydney region

**Comment by ujwalbukka** [comment]
@chalcrow Looks like 'sam build' step has failed. 
As mentioned under [Setting up the environment](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas#setting-up-the-environment) please make sure for Cloud9 instance you are using t3.large instance and volume size is 50 GB.
And also make sure you met all the [pre-requisites](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas#pre-requisites)

**Comment by chalcrow** [comment]
Thanks @ujwalbukka that resolved my issues. To get this reference solution to run in Cloud9, I also cloned the _workshop_ repo inside Cloud 9, using `git clone https://github.com/aws-samples/aws-serverless-saas-workshop.git`

After cloning that repo, I ran through the steps [here ](https://catalog.us-east-1.prod.workshops.aws/workshops/b0c6ad36-0a4b-45d8-856b-8a64f0ac76bb/en-US/pre-requisites/12-own-aws-account#installing-the-pre-requisites) to increase the Cloud9 EC2 instance size and install the prerequisites 

It seems that `template.yml` is an artifact that's produced at some stage of the deployment process, and that this wasn't being created due to insufficient memory size of the EC2 instance? Could you please confirm if this is correct, and if so, at what stage during the deployment that `template.yml` is created as an artifact?

**Comment by ujwalbukka** [comment]
@chalcrow when we run the [sam build](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/blob/main/deployment.sh#L48) it generates this template.yaml at .aws-sam/build/template.yaml. You can see this once sam build step is completed successfully in the terminal.

And when you run  [sam deploy](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/blob/main/deployment.sh#L49) it looks for this template file i.e., template.yaml or template.yml as mentioned in this [documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html)

When we run sam build it pulls bunch of docker images..etc to build this environment and it needs more space than default 10GB so we have to increase the volume size.

Hope this helps.

**Comment by ujwalbukka** [comment]
Closing this issue. Please reopen if you still have any issues/questions.
