### ISSUE TITLE
Stack cannot be updated when status is: UPDATE_ROLLBACK_COMPLETE

### ISSUE THREAD

**Issue by Ziems** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#21]
I caused a few issues in `tenant-template.yaml` which caused an update to fail.

After fixing the issue, `stack-pooled` is stuck on `UPDATE_ROLLBACK_COMPLETE` and anytime I try to deploy again or push to cc main, the stack wont update. The following error is given:

```
Stack cannot be updated when status is: UPDATE_ROLLBACK_COMPLETE
```

Is there a way to get it out of this state? I believe I've fixed all the issues in my tenant-template.

I have a feeling adding 'UPDATE_ROLLBACK_COMPLETE' to one or more of the status lists in `lambda-deploy-tenant-stack.py` would fix the issue, but so far every time I've tried it doesn't work.

Any help is appreciated. Thanks!

**Comment by ujwalbukka** [comment]
@Ziems - Yes, if you add 'UPDATE_ROLLBACK_COMPLETE' to the [status list](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/blob/main/server/TenantPipeline/resources/lambda-deploy-tenant-stack.py#L221) in `lambda-deploy-tenant-stack.py` would fix this issue.

**Comment by ujwalbukka** [comment]
@Ziems - Yes, if you add 'UPDATE_ROLLBACK_COMPLETE' to the [status list](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/blob/main/server/TenantPipeline/resources/lambda-deploy-tenant-stack.py#L221) in lambda-deploy-tenant-stack.py would fix this issue.

**Comment by ujwalbukka** [comment]
Closing this issue. Please reopen if you still have any issues/questions.
