### ISSUE TITLE
Usage Plans & API Keys

### ISSUE THREAD

**Issue by mk0e** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#23]
Hi,

first of all, thank you very much for this great example repo.

I have a question regarding the following section from the documentation: [Usage Plans & Reserved Concurrency by Tenant Tiers](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/blob/main/DOCUMENTATION.md#usage-plans--reserved-concurrency-by-tenant-tiers)

In there it says: *"... We have associated the API keys with these usage plans to ensure tenant level throttling limits."*

Now to my question:
Looking at the code I can see that there are 4 usage plans reflecting the different tiers. Each usage plan also has 1 predefined API key assigned. The API keys are coming from the Lambda Authorizer during the execution. 
What I am missing here is how this actually throttles requests on tenant level? If I have multiple tenants in 1 tier that are being mapped to the same API key behind the scenes, aren't they throttled on tier level then? Since the usage plans also have quotas configured, the usage of one tenant (in the basic tier for example the quota is 1000) would also influence the other tenants of this tier. This means if one tenant does 900 calls a day a second tenant can only do 100. Or am I missing something here?

Thanks in advance

**Comment by ujwalbukka** [comment]
Hi @mk0e 

In the current reference implementation we have created usage plans per tier and you are correct here all tenants in the tier will share the limits. 
As mentioned in the [Usage Plans & Reserved Concurrency by Tenant Tiers](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/blob/main/DOCUMENTATION.md#usage-plans--reserved-concurrency-by-tenant-tiers) "_Depending upon your scenario, you might consider having one usage plan per tenant as well_" you can create one usage plan per tenant.
