### ISSUE TITLE
Recent @types/prettier release breaks TypeScript build of TenantPipeline 

### ISSUE THREAD

**Issue by chalcrow** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#27]
The TenantPipeline currently fails to build (during initial creation via the main `./deployment.sh`) unless the TypeScript package version is updated in the `package.json` for the pipeline. Apparently this is due to a breaking change in a recent `@types/prettier` package release

I fixed the issue by updating to "typescript": "^4.2.0" in the `package.json` for the TenantPipeline

A description of the issue including the error encountered is at - https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/60314

**Comment by suhussai** [comment]
Hi @chalcrow , thanks for reporting this issue and providing the link. This error is also reported in the CDK public repo. You can find it here: https://github.com/aws/aws-cdk/issues/20319

The solution mentioned there is to pin the `@types/prettier` package to `2.6.0` in the `devDependencies` section in the `package.json` file, which is the fix included in this open PR https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/pull/25. If, for some reason, that does not work for you, please let us know and we will take another look.

We are reviewing that PR and plan to merge it into the main branch soon.

**Comment by suhussai** [comment]
#25 has been merged. Can you try updating your repo and re-running the `deployment.sh` script?

**Comment by ujwalbukka** [comment]
Closing this issue. Please reopen if you still have any issues/questions.
