### ISSUE TITLE
Adding a custom subdomain for each new tenant

### ISSUE THREAD

**Issue by babaksd** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#28]
I thought it might be a good idea to manage a custom domain/subdomain name for each new tenant in this reference solution. 
So each tenant will have its own subdomain to access the SAAS web app.

Thank you!

**Comment by ujwalbukka** [comment]
@babaksd - Yes, you can implement this subdomain approach, we did mentioned about this in the [documentation](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/blob/main/DOCUMENTATION.md#login-as-an-onboarded-tenant) in Step3.

If you are interested in understanding how to implement this approach, please refer to [EKS SaaS Reference Solution](https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture) which implemented this subdomain approach.

**Comment by babaksd** [comment]
Hi @ujwalbukka 

I'm trying to deploy the solution in AWS but the "serverless-saas-CustomResources" stack creation is stuck, Specifically, the "UpdateTenantStackMap" and "UpdateSettingsTable" events are stuck due to following errors from Cloudwatch:

   **Unable to import module 'update_settings_table': No module named 'logger' Traceback** 
   **Unable to import module 'update_settings_table': No module named 'crhelper' Traceback** 
   **Unable to import module 'update_tenantstackmap_table': No module named 'logger' Traceback** 
   **Unable to import module 'update_tenantstackmap_table': No module named 'crhelper' Traceback** 

It seems the Python dependencies are not installed correctly. 

May I ask you how can I fix that?

Thanks,

**Comment by ujwalbukka** [comment]
Hi @babaksd  - As mentioned in this [issue response](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/issues/5#issuecomment-860769337) please make sure you have latest sam cli version. 

And please make sure you have met all these [pre-requisites](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas#pre-requisites)
