### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by c4hinnova** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#3]
Greetings to all, in the deployment this error appears, I would like to know why it is and how I solve it to continue with the implementation.

Error en la ejecución de la acción
Build terminated with state: FAILED

[Container] 2021/05/29 17:57:06 Waiting for agent ping
2 | [Container] 2021/05/29 17:57:09 Waiting for DOWNLOAD_SOURCE
3 | [Container] 2021/05/29 17:57:10 Phase is DOWNLOAD_SOURCE
4 | [Container] 2021/05/29 17:57:10 CODEBUILD_SRC_DIR=/codebuild/output/src568487777/src
5 | [Container] 2021/05/29 17:57:10 Phase complete: DOWNLOAD_SOURCE State: FAILED
6 | [Container] 2021/05/29 17:57:10 Phase context status code: YAML_FILE_ERROR Message: stat /codebuild/output/src568487777/src/server/tenant-buildspec.yml: no such file or directory
7
<br class="Apple-interchange-newline">

Phase details:

DOWNLOAD_SOURCE | Error | YAML_FILE_ERROR: stat /codebuild/output/src568487777/src/server/tenant-buildspec.yml: no such file or directory
-- | -- | --

Thanks for your attention

**Comment by ujwalbukka** [comment]
@c4hinnova can you please provide more details on what steps you followed and when you encountered this error.
Is the deployment.sh script completed successfully? 
Do you see "serverless-saas-pipeline" stack under AWS CloudFormation service successfully completed?

**Comment by c4hinnova** [comment]
@ujwalbukka in codecommit the ZIP of the repository was loaded because it could not be cloned directly. but the "Source" step in codepipeline says "successful"

for:  the deployment.sh script completed successfully? Yes

for: Do you see "serverless-saas-pipeline" stack under AWS CloudFormation service successfully completed? it is say create complete. But in "Events" there are many with status "in progress" reason: "Resource creation Initiated" or "User Initiated"

Thanks

**Comment by ujwalbukka** [comment]
It looks like codebuild is unable to find/download the source code from artifact bucket used by codepipeline.
Is the artifact bucket got created in the same region where codebuild is running?
 
And also please make sure all the [pre-requisites](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas#pre-requisites) are met.

**Comment by anubhavynr** [comment]
@c4hinnova : is this still an issue for you?

**Comment by anubhavynr** [comment]
This doesn't seems to be an issue as per our testing. Please reopen if you are able to reproduce
