### ISSUE TITLE
deployment.sh error - as part of postinstall

### ISSUE THREAD

**Issue by Simonl9l** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#30]
Have all the prerequisites set up per the instructions!

> build
> ng build --prod --aot --build-optimizer --common-chunk --vendor-chunk --optimization --progress

Option "extractCss" is deprecated: Deprecated since version 11.0. No longer required to disable CSS extraction for HMR.
✔ Browser application bundle generation complete.

Error: ./node_modules/flag-icon-css/css/flag-icon.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /<path>/aws-saas-factory-ref-solution-serverless-saas/clients/Admin/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:388:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:719:3)
    at resolveExports (node:internal/modules/cjs/loader:488:36)
    at Module._findPath (node:internal/modules/cjs/loader:528:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:932:27)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/<path>/aws-saas-factory-ref-solution-serverless-saas/clients/Admin/node_modules/css-loader/dist/index.js:12:39)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)

**Comment by suhussai** [comment]
Hi @Simonl9l , I re-ran the `deployment.sh` script earlier today from a pristine clone and didn't run into any issues. Can you provide more specifics on the steps you took and the versions you are using for the following:

- npm
- node

Can you also include more of the script output, if possible? I think it'd be helpful to see some output before the error message.

**Comment by Simonl9l** [comment]
@suhussai yes apologies we can close it was a node/Angular incompatibility. Thanks for getting back to me,

**Comment by suhussai** [comment]
No worries! 👍

**Comment by Simonl9l** [comment]
@suhussai it might be good to update the docs to note the supported node/Angular versions - given some unfamiliarity to Angular.

Also of note but nothing that can be done from an Angular perspective it seems - node v12 is pretty much EOL - is there a plan to update these samples?

**Comment by suhussai** [comment]
@Simonl9l , were the minimum versions listed in the pre-requisites section (https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas#pre-requisites) not working for you?

**Comment by Simonl9l** [comment]
@suhussai seems (no expert here) that environment versioning is complex, and that “above” is not entirely true.

See that [this](https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3) seems to document current Angular comparability. 

I also see that per “Pre Requisites” for the CDK [here](https://docs.aws.amazon.com/cdk/v2/guide/getting_started.html) it advocates v16 of node.

So managing against all these dependencies is complex, not that you can do much about the state of Angular (behind-ness) compatibility.

I had node 18 installed, but needed to downgrade to 14 to get this sample and node 12 to get another aws sample to work. Per [this](https://nodejs.org/en/about/releases/) it seems node 12 is no longer even in maintenance

**Comment by suhussai** [comment]
@Simonl9l , thanks for the links and for clarifying the problem. I'll add this to our internal backlog with the info you provided.

**Comment by ujwalbukka** [comment]
Closing this issue. Please reopen if you still have any issues/questions.

**Comment by suhussai** [comment]
@Simonl9l , I just wanted to follow-up here; we've updated the dependencies in this sample to use angular v14. I recently deployed the setup myself using Node v16 and can confirm it works as expected. If you happen to deploy this sample again, please let us know if you have any other feedback. Thanks!
