### ISSUE TITLE
Can't find anything on AWS Console after successful run of deployment.sh

### ISSUE THREAD

**Issue by lwang168** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#33]
I was able to run deployment.sh successful, and can access Admin/Application/Landing URLs, but when I go to CodePipeline on AWS Console, I don't see any pipeline/build/deployment. What am I missing?

**Comment by lwang168** [comment]
Thanks for the response. I do see multiple stacks on the CloudFormation console.

**Comment by ujwalbukka** [comment]
@lwang168 - In the Cloudformation console, do you see a stack with name "serverless-saas-pipeline" successfully completed? This is the stack which takes care of creating codepipeline.

**Comment by lwang168** [comment]
Yes, with the status "UPDATE_COMPLETE".

This is what happened. The first time I ran deployment.sh, it failed, but I remember I saw entries in CodePipeline build/deployment/pipeline. I deleted them.

Then I fixed issues from prior runs, and re-ran deployment.sh successfully, but no entries in CodePipeline. Is this expected behavior? How do I re-create entries in CodePipeline?

**Comment by ujwalbukka** [comment]
If "serverless-saas-pipeline" stack has completed successfully then the code pipeline might have created. 
Are you looking in the correct region? In the AWS console go the CodePipeline service in the same region where you have deployed the Serverless SaaS Reference solution then in the left menu under "Pipeline" click on "Pipelines" and you should see it.

You can redeploy code pipeline by just running the code in deployment.sh from [L18](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/blob/main/deployment.sh#L18) to L22

**Comment by lwang168** [comment]
Thanks for your help. I believe I use the same region us-east-1. See attached screenshots of CloudFormation and CodePipeline.

![CloudFormation](https://user-images.githubusercontent.com/59580636/178841921-65dc158d-57a9-4d0c-bd3f-993d00aac151.JPG)
![CodePipeline](https://user-images.githubusercontent.com/59580636/178841925-93153e97-1aa7-45ff-8344-1a457387b75a.JPG)

**Comment by ujwalbukka** [comment]
Did you tried redeploying the 'serverless-saas-pipeline' stack? If possible delete the 'serverless-saas-pipeline' stack first and then redeploy.

You can redeploy by just running the code in deployment.sh from [L18](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/blob/main/deployment.sh#L18) to L22
Or you can just rerun the whole deployment.sh script.

**Comment by lwang168** [comment]
It works by deleting "serverless-saas-pipeline" stack and redeploying. Thanks for the help.
