### ISSUE TITLE
DeployTenantStack CodePipeline action fails

### ISSUE THREAD

**Issue by DanyC97** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#4]
Hi,

On a fresh deployment it looks like the deployment fails because the `DeployTenantStack` action name part of the CodePipeline `Deploy` stage fails with the below error

```
The AWS Lambda function serverless-saas-pipeline-deploytenantstackD22DC62B-5ksnb3c9qn57 failed to return a result. Check the function to verify that it has permission to call the PutJobSuccessResult action and that it made a call to PutJobSuccessResult.
```

I think the error is misleading because the lambda has the right permission to push the job back to CodePipeline and in the CW logs i can see the lambda completed w/o an error.

Could it be because of [this](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/blob/849c67d24b0f05398d745b0e6333623f3c5a4fd6/server/TenantPipeline/resources/lambda-deploy-tenant-stack.py#L474) ?

**Comment by ujwalbukka** [comment]
You mentioned Lambda CloudWatch logs does not have errors, where are you seeing this error?
Did the deployment.sh script completed successfully?
Did the codepipeline "serverless-saas-pipeline" execution completed successfully?

And also please make sure all the [pre-requisites](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas#pre-requisites) are met.

**Comment by DanyC97** [comment]
> You mentioned Lambda CloudWatch logs does not have errors, where are you seeing this error?

in the pipeline stage - see below

> Did the deployment.sh script completed successfully?

Negative, it error out

> Did the codepipeline "serverless-saas-pipeline" execution completed successfully?
> 

Negative, that is where i've saw the error, the `Deploy` stage failed - see below

![image](https://user-images.githubusercontent.com/7383422/121746305-94fbd200-cafd-11eb-80d3-2b9cc809e9a6.png)

> And also please make sure all the [pre-requisites](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas#pre-requisites) are met.

sure thanks, will review it again and have another go

**Comment by anubhavynr** [comment]
@DanyC97 : Were you able to test this and resolve?

**Comment by DanyC97** [comment]
hi @anubhavynr , yes i was able to re-run the test and i've bumped into same issue even after the pre-req were done correctly.

After i've rolledback the commented [line](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/blob/849c67d24b0f05398d745b0e6333623f3c5a4fd6/server/TenantPipeline/resources/lambda-deploy-tenant-stack.py#L474) i was able to get it all working

**Comment by DanyC97** [comment]
re-tested again couple of times in last 60 min and couldn't reproduce it hence going to close it
