### ISSUE TITLE
Login to Tenant UI is failing

### ISSUE THREAD

**Issue by dprog22** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#43]
<img width="768" alt="Screen Shot 2022-10-27 at 1 08 56 PM" src="https://user-images.githubusercontent.com/108850348/198389255-9d923401-e9c0-45bd-8c33-ed856265969f.png">

**Comment by anubhavynr** [comment]
The tenant name should match with the name used while onboarding the tenant. Please check with TenantManagement DynamoDB and confirm if this tenant exists with this name

**Comment by dprog22** [comment]
Obviously the “tenant name” I created and tried login was same. The
TenantManagement table in DynamoDB doesn’t have any entries.
Looks like nobody ever tried to use the code as is?

**Comment by anubhavynr** [comment]
If the Tenant management table is empty then you haven't onboarded any tenants or some error occurred while onboarding a tenant. This reference solution is being used widely and we are not aware of any such issue. Can you please provide any errors you faced while onboarding?

Also you can follow below workshop to get a step-by-step understanding of the reference solution.
https://github.com/aws-samples/aws-serverless-saas-workshop

**Comment by dprog22** [comment]
Yes, we followed the workshop. It's badly broken at several places. Please
deploy & QA it once again.

Here are some of the logs .. There are two errors happening now -
1. When i try to create a user - i get the following error -
[ERROR] ResourceNotFoundException: An error occurred
(ResourceNotFoundException) when calling the AdminAddUserToGroup operation:
Group not found.
Traceback (most recent call last):
  File "/opt/python/aws_lambda_powertools/tracing/tracer.py", line 305, in
decorate
    response = lambda_handler(event, context, **kwargs)
  File "/var/task/user-management.py", line 90, in create_user
    user_mgmt.add_user_to_group(user_pool_id, user_details['userName'],
user_tenant_id)
  File "/var/task/user-management.py", line 342, in add_user_to_group
    response = client.admin_add_user_to_group(
  File "/opt/python/botocore/client.py", line 495, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/aws_xray_sdk/ext/botocore/patch.py", line 38, in
_xray_traced_botocore
    return xray_recorder.record_subsegment(
  File "/opt/python/aws_xray_sdk/core/recorder.py", line 436, in
record_subsegment
    return_value = wrapped(*args, **kwargs)
  File "/opt/python/botocore/client.py", line 914, in _make_api_call
    raise error_class(parsed_response, operation_name)

2. After Lab3 instructions, unable to now view the user list which was
visible till lab 2 and no code has changed in the get call.
attached is the screenshot

Further info -
logs for get users is showing as an unauthorized call

{
    "level": "INFO",
    "location": "log_with_tenant_context:19",
    "message": "Request completed as unauthorized.",
    "timestamp": "2022-11-04 01:42:29,079+0000",
    "service": "UserManagement.GetUsers",
    "tenant_id": "mongo",
    "xray_trace_id": "1-63646e01-1a5de0670f34422210da1555"
}

[image: Screen Shot 2022-11-04 at 6.43.57 PM.png]

**Comment by anubhavynr** [comment]
We recently had few test runs of the workshop. One was completed last Friday itself. No errors or issues reported were reported. 

Can you please provide the Lab and Step for first error? Will try one more time.

Your second error seems like your JWT token might have expired (unauthorized). Please log off and login back again and let me know if that works.

**Comment by ujwalbukka** [comment]
Hi @dprog22 

Just wanted to check, if you got a chance to test it again? are you still running into any issues?

**Comment by dprog22** [comment]
Still running into lots of issues. Planning to recreate it today and debug
with Anubhav at 9am PDT today.

**Comment by anubhavynr** [comment]
Focussing on workshop.... I tried creating user from both SaaS Admin and SaaS application and was able to do that successfully. As discussed, let's focus on workshop to understand how the reference solution works first and then you can deploy the reference solution and play around with it.
