### ISSUE TITLE
All lambdas CW logs show error importing the logger module

### ISSUE THREAD

**Issue by DanyC97** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#5]
I've tried deploying into us-east-1/2 but no luck.

What i see in the CW logs for say `
/aws/lambda/serverless-saas-LambdaFun-UpdateTenantStackMapTabl-IvNpHXeVlav7` is

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'update_tenantstackmap_table': No module named 'logger'
Traceback (most recent call last):

```

Tracing back it seems like something might be wrong with the lambda insight because in the lambda itself i see the 2 layers

![image](https://user-images.githubusercontent.com/7383422/121747579-89a9a600-caff-11eb-886d-60e05bc666ee.png)

but i don't see the layer in the dashboard - shouldn't that appear ?

![image](https://user-images.githubusercontent.com/7383422/121747632-9fb76680-caff-11eb-82bd-fafa2c82b4bd.png)

Sadly i don't see any other error ...

**Comment by DanyC97** [comment]
maybe the lambdainsights layer has nothing to do here  ... very confused

**Comment by DanyC97** [comment]
and because the 2 custom resources  - `UpdateSettingsTable` & `UpdateTenantStackMap` part of the tenant stack `serverless-saas-CustomResources`  it goes into a fail loop of 3x, after that it won't retry and as such the CFN  will timeout ... eventually.

This is vv odd issue as the layer is present and the above CFN has a dependency condition in the root / parent cfn stack ...i'm losing the battle

**Comment by ujwalbukka** [comment]
One instance where you will encounter this below is issue when you have a sam cli version < 1.20.0, we are using nested templates and they are supported only from sam cli version 1.20.0.  

Please check if you have latest version of sam cli version.

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'update_tenantstackmap_table': No module named 'logger'
Traceback (most recent call last):
```

**Comment by DanyC97** [comment]
oh i see, i'll go and have a go at this in a min. The below version is present in Cloud9 and so i thought that is good enough to get me starting (i should have listen and follow your notes)


```
 sam --info
{
  "version": "1.19.0"
}
```

**Comment by DanyC97** [comment]
Closing the issue as it was indeed caused by the old version of sam cli ....how annoying this was but lesson learn to read carefully the pre-req and not rely on already installed version
