### ISSUE TITLE
[Question] tenant/init endpoint could be misused for scraping

### ISSUE THREAD

**Issue by hffmnn** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#50]
From my perspective it is a little bit concerning, that the admin-api `GET` endpoint `tenant/init`  could be misused to scrape potential tenant names of the service which in turn would hand out some information about potential customers to anyone who is interested.

What do you think?

**Comment by ujwalbukka** [comment]
The challenge we are trying to solve here is mapping a user to an identity provider(Cognito userpool in this case). As your architecture can have multiple Cognito user pools.  

Alternate approaches
1. Can have a subdomain per each tenant i.e., tenant1.example.com if request comes from this domain you can redirect to its identity provider for authentication
2. Can use domain name from email address and redirect to its identity provider for authentication
3. You can first authenticate the user then show the list of tenants they belong too. If they belong to one tenant you can just redirect them to that tenant space.

**Comment by anubhavynr** [comment]
As Ujwal mentioned, that init endpoint is being used for discovery purposes. We just decided to use TenantName for the sake of simplicity, you can use other mechanisms as listed above.
