### ISSUE TITLE
AppSync with temp creds from Authorizer lambda

### ISSUE THREAD

**Issue by joa44741** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#59]
Hey, 

I want to use your ref-solution but I wondered if I could get rid of some lambda functions in my project and instead use AppSync with DynamoDB directly. 
Is it possible that AppSync could forward the generated temporary credentials for the tenant (from the Authorizer Lambda) to the DynamoDB call? 

Best regards

**Comment by anubhavynr** [comment]
It will not be possible with direct integration using DynamoDB resolver. But you should be able to use the tenant id directly from context to make the get call inside the resolver.

**Comment by ujwalbukka** [comment]
Closing this issue. Please reopen if you still have any issues/questions.
