### ISSUE TITLE
error when creating a platinum plan tenant

### ISSUE THREAD

**Issue by antholopez** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#61]
error when creating a platinum plan tenant

When I create a tenant with a platinum plan from the SaaS Admin, the provisioning is not generated correctly and an error occurs in cloud formation

![image](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/assets/55224854/3644a45d-39e8-4ee9-82be-72e4b62bd25b)

I have not made any modifications to the source code.

![image](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/assets/55224854/89662b03-cc43-43c4-9706-edc31cdc660e)

Note: This happens when I create a second admin tenant

**Comment by suhussai** [comment]
hi @antholopez , can you provide click on the Events tab to see if there are any errors there?

**Comment by ujwalbukka** [comment]
Closing the issue. Please feel free to re-open it if you still have questions/issues
