### ISSUE TITLE
Cannot access the templates

### ISSUE THREAD

**Issue by raffaellanz** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#70]
When is trying to build the serverless-saas stack , get the following error:

```
 "CREATE_FAILED                  AWS::CloudFormation::Stack     DynamoDBTables                 Embedded stack               
                                                                                             arn:aws:cloudformation:ap-so 
                                                                                             utheast-                     
                                                                                             2:058264145775:stack/serverl 
                                                                                             ess-saas-DynamoDBTables-     
                                                                                             D1CVNO4IMHRI/7ee0d410-b33b-  
                                                                                             11ee-9454-02783fdb39f1 was   
                                                                                             not successfully created:    
                                                                                             The following resource(s)    
                                                                                             failed to create:            
                                                                                             [TenantDetailsTable,         
                                                                                             TenantUserMappingTable,      
                                                                                             ServerlessSaaSSettingsTable, 
                                                                                             TenantStackMappingTable].    
CREATE_FAILED                  AWS::CloudFormation::Stack     UserInterface                  Resource creation cancelled  
```" 

and it looks like the referred template "https://s3.ap-southeast-2.amazonaws.com/sam-bootstrap-bucket-bb9ea330-4c26-428a-abf8-cfc40a8bd92b/serverless-saas-bootstrap/a82399651c1cb502dcd3b66d24de903f.template" is not accessible as going directly to that address I get :
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>1SABXHEQDXJ20KG8</RequestId>
<HostId>AYHQ2rY3YID/HQGmIefXCWsJzX2utAp4IfpzE3CRevRBn5qPC+o7MNEjPvq7VT5CCfcAEKvw+i4=</HostId>
</Error>
```

If I tried the non region endpoint https://s3.amazonaws.com/sam-bootstrap-bucket-bb9ea330-4c26-428a-abf8-cfc40a8bd92b/serverless-saas-bootstrap/a82399651c1cb502dcd3b66d24de903f.template and I get 
```
<Error>
<Code>PermanentRedirect</Code>
<Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message>
<Endpoint>sam-bootstrap-bucket-bb9ea330-4c26-428a-abf8-cfc40a8bd92b.s3.amazonaws.com</Endpoint>
<Bucket>sam-bootstrap-bucket-bb9ea330-4c26-428a-abf8-cfc40a8bd92b</Bucket>
<RequestId>0P9MMAA5KCPG0JHY</RequestId>
<HostId>RKN6R3A4V5twGTyUs+A8+GQTiNDDQB26gWE7o+nksba4dw/IzTD1JtMfuFEMcxUyFbm12Jt/3T4=</HostId>
</Error>
```

**Comment by ujwalbukka** [comment]
Hi @raffaellanz - Looks like nested stack **serverless-saas-DynamoDBTables** failed to deploy. Can you please check that stack in Cloudformation to see with what error it has failed.

**Comment by ujwalbukka** [comment]
Closing the issue. Please feel free to re-open it if you still have questions/issues

**Comment by raffaellanz** [comment]
What I reported is the only error information. No more details in CloudFormation

**Comment by ujwalbukka** [comment]
Hi @raffaellanz  - I was successfully able to deploy the reference solution in ap-southeast-2 region.

1. On which Cloud9 instance are running this on? Amazon Linux 2? 
2. Did you ran [increase-disk-size.sh](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/blob/main/Cloud9Setup/increase-disk-size.sh) and [pre-requisities.sh](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/blob/main/Cloud9Setup/pre-requisites.sh) scripts before deploying reference solution?  If yes, can you please run [pre-requisites-version-check.sh](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/blob/main/Cloud9Setup/pre-requisites-versions-check.sh) script to validate if everything has been deployed correctly or not.
3. Are you able to see **serverless-saas-DynamoDBTables** stack? maybe it might under **Failed or Deleted** status, try to change the **Filter status** in CloudFormation and see if you can find the stack and its error.
