### ISSUE TITLE
Website changes do not seem to update the S3 buckets serving the web pages to Cloud Front

### ISSUE THREAD

**Issue by kevin-pieroni** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#76]
This may be a misunderstanding of the deployment process in Step Functions. However after a successful code commit changeset to update the landing page website (title and header) the build pipelines executes and completes successfully but does not update the S3 buckets used by Cloud Front to serve the web pages for the landing website. I can see that the staging S3 bucket for build artifacts is updated with the latest changes, however I cannot see a reference in the pipeline to deploy the website artifacts to the S3 buckets. Is this by design or am I missing something? Thank you.

**Comment by ujwalbukka** [comment]
Closing the issue. Please feel free to re-open it if you still have questions/issues
