### ISSUE TITLE
CodeCommit is deprecated

### ISSUE THREAD

**Issue by royaltwets** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#87]
As per [this](https://github.com/aws-samples/saas-reference-architecture-ecs/issues/18#issue-2469319924) issue in the ECS reference sbt architecture, CodeCommit is deprecated and the install.sh script fails as a result

**Comment by ujwalbukka** [comment]
Hi @royaltwets - Thanks for reporting this issue. We are working on fixing this.

**Comment by bparvizi-aws** [comment]
@royaltwets we have migrated the source repository from AWS CodeCommit to Amazon S3. Please let us know if you encounter any other issues. Thank you!

**Comment by ujwalbukka** [comment]
Closing the issue. Please feel free to re-open it if you still have questions/issues
