### ISSUE TITLE
The AWS Lambda function serverless-saas-pipeline-deploytenantstackD22DC62B-6XvRfhFW0DkC failed to return a result

### ISSUE THREAD

**Issue by mayurschavan** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#9]
Action execution failed
The AWS Lambda function serverless-saas-pipeline-deploytenantstackD22DC62B-6XvRfhFW0DkC failed to return a result. Check the function to verify that it has permission to call the PutJobSuccessResult action and that it made a call to PutJobSuccessResult.
![Screenshot 2021-09-17 at 12-42-48 CodePipeline - AWS Developer Tools](https://user-images.githubusercontent.com/39122238/133740435-34303c89-c64c-49d1-9ea4-d012c687dd63.png)

**Comment by mayurschavan** [comment]
I am using cloud9 t3.large instance to deploy this ref saas solution, but receiving error. and stack keeps showing create in progress
![Screenshot 2021-09-17 at 12-45-28 CloudFormation - Stack](https://user-images.githubusercontent.com/39122238/133740825-f038f3cd-09b1-4dda-8ebd-d0e9d61dea5d.png)

**Comment by anubhavynr** [comment]
Can you please click on the execution details and see if there is any additional information in the cloudwatch logs?

We highly recommend that you install all the pre-requisites first. You can perform clean-up steps, install pre-requisites and try again if you want.

**Comment by mayurschavan** [comment]
![Capture_cloudwatch](https://user-images.githubusercontent.com/39122238/133818313-6be8d85c-cefa-467c-9fc3-06fafd6a18f4.JPG)

**Comment by mayurschavan** [comment]
Any Update?

**Comment by anubhavynr** [comment]
We are not able to reproduce the issue and the logs you provided don't provide any information to guide you further.

As I mentioned before, please perform clean-up steps in your account, install pre-reqs and try again. Pay special attention to pre-reqs and make sure that sam and aws cdk are latest.
